[package]
name = "stage_1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i386 = { path = "../../../../i386" }
shared = { path = "../shared" }
