[package]
name = "stage_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i386 = { path = "../../i386" }
shared = { path = "../shared" }
static-alloc = "0.2.3"
spin = "0.9.2"
