start: 0
end: 0x100000
stages:
  - name: "stage1"
    meta:
      start: 0x7c00
    sections:
      body: 0x7c00 # BIOS 1st sector load address
  - name: "stage2"
    meta:
      start: 0x7e00
      entry: 0x7e00
    sections:
      body: 0x7e00 # stage 2 load address
      gdt: 0xff00
  - name: "stage3"
    meta:
      start: 0x10000
      entry: 0x10000
    sections:
      body: 0x10000
      data: 0x22000
  - name: "global"
    meta: 
      start: 0x30000
    sections:
      heap: 0x40000 # a global heap
      stack_top: 0x50000
      stack_but: 0x60000
      video: 0xb8000
  - name: "kernel"
    meta:
      start: 0x100000
      end: 0x200000
    sections:
      body: 0x100000